# -*- coding: utf-8 -*-
"""DSA210-PROJECT

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IgEBAgqyUWqLQBhVhhB9ovA0tBTGYCP8
"""

import pandas as pd
import json
import glob
import os
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats

# 1st STEP: I'm merging my all Spotify streaming history data..

json_files = glob.glob("Streaming_History_Audio_*.json")
all_records = []

for file in json_files:
    with open(file, 'r', encoding='utf-8') as f:
        data = json.load(f)
        all_records.extend(data)

# I'm creating my main DataFrame.
df = pd.DataFrame(all_records)

# I'm cleaning dates.
df['ts'] = pd.to_datetime(df['ts'])
df['date_only'] = df['ts'].dt.date


# 2nd STEP: I'm loading my academic stress, crying, and menstrual data..

# 1. Academic Stress
stress_df = pd.read_csv('academic_stress.csv')
stress_df['Start_Date'] = pd.to_datetime(stress_df['Start_Date'], dayfirst=True).dt.date
stress_df['End_Date'] = pd.to_datetime(stress_df['End_Date'], dayfirst=True).dt.date

# 2. Menstrual Data (I'm checking if the file exists because it is private and I haven't directly uploaded it to GitHub--it is in .gitignore)
period_df = pd.read_csv('menstrual_data.csv') if os.path.exists('menstrual_data.csv') else None
if period_df is not None:
    period_df['Start_Date'] = pd.to_datetime(period_df['Start_Date'], dayfirst=True).dt.date
    period_df['End_Date'] = pd.to_datetime(period_df['End_Date'], dayfirst=True).dt.date

# 3. Crying Logs (Again, I'm checking if the file exists because it is private and I haven't directly uploaded it to GitHub--it is in .gitignore)
crying_df = pd.read_csv('crying_logs.csv') if os.path.exists('crying_logs.csv') else None
if crying_df is not None:
    crying_df['Date'] = pd.to_datetime(crying_df['Date'], dayfirst=True).dt.date


# 3rd STEP: I'm integratingg..

# This function maps each song to my personal state on that day.
def get_daily_context(current_date):

  stress_val = 2
  crying_val = 0
  period_val = 0

  # Matching stress
  for _, row in stress_df.iterrows():
      if row['Start_Date'] <= current_date <= row['End_Date']:
          stress_val = row['Stress_Level']
          break

  # Matching period
  if period_df is not None:
      for _, row in period_df.iterrows():
          if row['Start_Date'] <= current_date <= row['End_Date']:
              period_val = 1
              break

  # Matching crying
  if crying_df is not None:
      if current_date in crying_df['Date'].values:
          crying_val = 1

  return pd.Series([stress_val, crying_val, period_val])

df[['stress_level', 'crying_incident', 'is_period']] = df['date_only'].apply(get_daily_context)

# 4th STEP: EDA (Visualization)..

plt.figure(figsize=(10,6))

# I'm calculating average listening duration in minutes per stress level.
eda_data = df.groupby('stress_level')['ms_played'].mean() / 60000
sns.barplot(x=eda_data.index, y=eda_data.values, palette='coolwarm')

plt.title('My Average Track Duration vs. My Stress Level')
plt.xlabel('Stress Level (Default=2, Max=5)')
plt.ylabel('Average Minutes Played')
plt.savefig('stress_listening_eda.png')
plt.show()

# 5th STEP: Hypothesis Testing..

# My Alternative Hypothesis: My average track duration significantly changes during exam weeks (Stress >= 4), as I am stressful.
normal_days = df[df['stress_level'] <= 2]['ms_played']
exam_days = df[df['stress_level'] >= 4]['ms_played']

t_stat, p_val = stats.ttest_ind(normal_days, exam_days)
print(f"T-Statistic: {t_stat:.4f}")
print(f"P-Value: {p_val:.4f}")

if p_val < 0.05:
    print("Conclusion: The difference is statistically significant.")
else:
    print("Conclusion: No significant difference is found.")

# 6th STEP: I'm exporting..

# I'm saving only relevant columns for the final submission.
final_cols = ['ts', 'master_metadata_track_name', 'ms_played', 'stress_level', 'crying_incident', 'is_period']
df[final_cols].to_csv('my_featurized_data.csv', index=False)
print("Files saved successfully!")